/*
 * This file is generated by jOOQ.
 */
package com.jooqpoc.model;

import javax.annotation.Generated;

import com.jooqpoc.model.tables.Client;

/**
 * Convenience access to all tables in library
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.9.0" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table <code>library.client</code>.
	 */
	public static final Client CLIENT = com.jooqpoc.model.tables.Client.CLIENT;
}
